### ISSUE TITLE
contact point

### ISSUE THREAD

**Issue by fmadio** [Open-Markets-Initiative/contents#2]
Hi, can someone reach out us support at fmad dot io for a conversion. we are really interested in supporting this project, thanks.

**Comment by Open-Markets-Initiative** [comment]
Hello, thanks for reaching out. Our tech lead is on vacation, and will get back to you mid-august.

**Comment by fmadio** [comment]
great thanks.

**Comment by Open-Markets-Initiative** [comment]
done

**Comment by fmadio** [comment]
thanks have sent reply on email.
