### ISSUE TITLE
No information about/access to codegen tools?

### ISSUE THREAD

**Issue by pierzchalski** [Open-Markets-Initiative/contents#3]
Several of the OMI project repos consist entirely of generated code, with a README saying that contributions should consist of requests for additional protocols. Can we have access to the codegen tools instead? That way contributions can consist of more than just asking for more protocols.

**Comment by Open-Markets-Initiative** [comment]
Some of the code gen tools will be open sourced when they are more complete.  The full set of code gen tools can be licensed (something inner market firms) would be wise to consider).  What are you trying to do?

**Comment by pierzchalski** [comment]
Thanks for the quick reply! I'm not sure what you mean by "inner markets"?

I'd like to investigate adding support for other languages (Python, Rust) as well as adding more protocols.

**Comment by Open-Markets-Initiative** [comment]
I don't know what "inner markets" are either.  I updated the comment... inner market firms that use direct exchange connections should use source generated code.  

Python is coming soonish.  We can make Rust with a model.    Do you want to chat outside of GitHub?

**Comment by pierzchalski** [comment]
Sure, I've just sent an email.

**Comment by Open-Markets-Initiative** [comment]
Did you check the email?
